sed 's/Amhara/Amhara/g' <	tmp1	> tmp2
sed 's/Baka_Cam/BakaC/g' <	tmp2	> tmp1
sed 's/Baka_Gab/BakaG/g' <	tmp1	> tmp2
sed 's/Bakiga/BaKiga/g' <	tmp2	> tmp1
sed 's/Bangweulu/Bangweulu/g' <	tmp1	> tmp2
sed 's/Batwa/Batwa/g' <	tmp2	> tmp1
sed 's/Bongo_GabE/BongoE/g' <	tmp1	> tmp2
sed 's/Bongo_GabS/BongoS/g' <	tmp2	> tmp1
sed 's/CEU/CEU/g' <	tmp1	> tmp2
sed 's/Chad_Sara/Sara/g' <	tmp2	> tmp1
sed 's/Chad_Toubou/Toubou/g' <	tmp1	> tmp2
sed 's/CHB/Han/g' <	tmp2	> tmp1
sed 's/ColouredAskham/Khomani/g' <	tmp1	> tmp2
sed 's/Ethiopia_Sabue/Sabue/g' <	tmp2	> tmp1
sed 's/GuiGhanaKgal/KhutseSan/g' <	tmp1	> tmp2
sed 's/Igbo/Igbo/g' <	tmp2	> tmp1
sed 's/Juhoansi/Juhoansi/g' <	tmp1	> tmp2
sed 's/Kafue/Kafue/g' <	tmp2	> tmp1
sed 's/Karretjie/Karretjie/g' <	tmp1	> tmp2
sed 's/Khomani/Khomani/g' <	tmp2	> tmp1
sed 's/Khwe/Khwe/g' <	tmp1	> tmp2
sed 's/LWK/Luhya/g' <	tmp2	> tmp1
sed 's/Mandinka/Mandinka/g' <	tmp1	> tmp2
sed 's/MKK/Maasai/g' <	tmp2	> tmp1
sed 's/Nama/Nama/g' <	tmp1	> tmp2
sed 's/Nzebi_Gab/Nzebi/g' <	tmp2	> tmp1
sed 's/Nzime_Cam/Nzime/g' <	tmp1	> tmp2
sed 's/Oromo/Oromo/g' <	tmp2	> tmp1
sed 's/schus/San/g' <	tmp1	> tmp2
sed 's/SEBantu/SEBantu/g' <	tmp2	> tmp1
sed 's/Somali/Somali/g' <	tmp1	> tmp2
sed 's/Sotho/Sotho/g' <	tmp2	> tmp1
sed 's/Sudan_Dinka/Dinka/g' <	tmp1	> tmp2
sed 's/SWBantu/Herero/g' <	tmp2	> tmp1
sed 's/Tanzania_Hadza/Hadza/g' <	tmp1	> tmp2
sed 's/Xun/Xun/g' <	tmp2	> tmp1
sed 's/YRI/Yoruba/g' <	tmp1	> tmp2
sed 's/Zambia_Bemba/Bemba/g' <	tmp2	> tmp1
sed 's/Zambia_Lozi/Lozi/g' <	tmp1	> tmp2
sed 's/Zambia_TongaZam/Tonga/g' <	tmp2	> tmp1
sed 's/Zulu/Zulu/g' <	tmp1	> tmp2
