sed 's/Amhara/Amhara_Ethiopia/g' <	tmp1	> tmp2
sed 's/Baka_Cam/Baka_Cameroon/g' <	tmp2	> tmp1
sed 's/Baka_Gab/Baka_Gabon/g' <	tmp1	> tmp2
sed 's/Bakiga/BaKiga_Uganda/g' <	tmp2	> tmp1
sed 's/Bangweulu/Bangweulu_Zambia/g' <	tmp1	> tmp2
sed 's/Batwa/Batwa_Uganda/g' <	tmp2	> tmp1
sed 's/Bongo_GabE/Bongo_GabonE/g' <	tmp1	> tmp2
sed 's/Bongo_GabS/Bongo_GabonS/g' <	tmp2	> tmp1
sed 's/CEU/CEU_US/g' <	tmp1	> tmp2
sed 's/Chad_Sara/Sara_Chad/g' <	tmp2	> tmp1
sed 's/Chad_Toubou/Toubou_Chad/g' <	tmp1	> tmp2
sed 's/CHB/Han_China/g' <	tmp2	> tmp1
sed 's/ColouredAskham/ColouredAskham_SA/g' <	tmp1	> tmp2
sed 's/Ethiopia_Sabue/Sabue_Ethiopia/g' <	tmp2	> tmp1
sed 's/GuiGhanaKgal/GuiGhanaKgal_Botswana/g' <	tmp1	> tmp2
sed 's/Igbo/Igbo_Nigeria/g' <	tmp2	> tmp1
sed 's/Juhoansi/Juhoansi_Namibia/g' <	tmp1	> tmp2
sed 's/Kafue/Kafue_Zambia/g' <	tmp2	> tmp1
sed 's/Karretjie/Karretjie_SA/g' <	tmp1	> tmp2
sed 's/Khomani/Khomani_SA/g' <	tmp2	> tmp1
sed 's/Khwe/Khwe_SA/g' <	tmp1	> tmp2
sed 's/LWK/Luhya_Kenya/g' <	tmp2	> tmp1
sed 's/Mandinka/Mandinka_Gambia/g' <	tmp1	> tmp2
sed 's/MKK/Maasai_Kenya/g' <	tmp2	> tmp1
sed 's/Nama/Nama_Namibia/g' <	tmp1	> tmp2
sed 's/Nzebi_Gab/Nzebi_Gabon/g' <	tmp2	> tmp1
sed 's/Nzime_Cam/Mzime_Cameroon/g' <	tmp1	> tmp2
sed 's/Oromo/Oromo_Ethiopia/g' <	tmp2	> tmp1
sed 's/schus/San_Namibia/g' <	tmp1	> tmp2
sed 's/SEBantu/SEBantu_SA/g' <	tmp2	> tmp1
sed 's/Somali/Somali_Ethiopia/g' <	tmp1	> tmp2
sed 's/Sotho/Sotho_SA/g' <	tmp2	> tmp1
sed 's/Sudan_Dinka/Dinka_Sudan/g' <	tmp1	> tmp2
sed 's/SWBantu/SWBantu_Namibia/g' <	tmp2	> tmp1
sed 's/Tanzania_Hadza/Hadza_Tanzania/g' <	tmp1	> tmp2
sed 's/Xun/Xun_Namibia/g' <	tmp2	> tmp1
sed 's/YRI/Yoruba_Nigeria/g' <	tmp1	> tmp2
sed 's/Zambia_Bemba/Bemba_Zambia/g' <	tmp2	> tmp1
sed 's/Zambia_Lozi/Lozi_Zambia/g' <	tmp1	> tmp2
sed 's/Zambia_TongaZam/Tonga_Zambia/g' <	tmp2	> tmp1
sed 's/Zulu/Zulu_SA/g' <	tmp1	> tmp2
